### PR TITLE
Temp dir creation issue + debug hepler

### PR DESCRIPTION
**Pull request by alexeygrigorev**
In this pull request there are two things:
- it used to create a temp file instead of a temp dir for storing the final result - fixed that
- now it also shows the final result for each task (by outputting to the console the content of the result files) - it helps to check if the code works 

I also added a small cosmetic modification - removed redundant interface declaration from the plans (`ProgramDescription` extends `Program`, so there's no need to declare the latter)

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for your pull request!
- Is it your intention that it contains the results of the exercises? The idea of the code is to provide a skeleton that "students" have to fill out.
- Providing tests for the code is a good idea. Students can then, test if parts of the code are already implemented.

**Comment by alexeygrigorev** [comment]
I'm sorry - no, it wasn't my intention, I actually committed the solutions after creating the pull request, I have no idea how it ended up there. I'll try to re-create my pull request.

**Comment by rmetzger** [comment]
Your pull request is based on your master branch. Everything you commit into that branch will appear in this pull request.
I recommend to create "feature branches" for creating pull requests.

**Comment by rmetzger** [comment]
In this situation, you can do the following:
Create a branch called "test-cases" or so:
git checkout -b test-cases origin/master
git cherry-pick 2cb0433
git cherry-pick fe46ef2

then, open a pull request against test-cases.

**Comment by alexeygrigorev** [comment]
Thanks Robert. Actually my intention was to fix a bug with creating a temp dir, but if you want, I can also include the tests.

**Comment by alexeygrigorev** [comment]
The correct one (hopefully) should be in the pull request #10 - thanks for helping to solve it

**Pull request closed without merging**
