### PR TITLE
Java exercise update to 0.4 api and minor spelling corrections

### PR DESCRIPTION
**Pull request by vasia**
Hey, I updated the Java exercise description. Let me know if you spot anything I forgot!

### CODE REVIEW

**Comment by rmetzger** [comment]
Hi Vasia,
thank you for the fix.

**Comment by rmetzger** [comment]
This PR resolved https://github.com/stratosphere/bigdataclass.org/issues/5.

**Comment by rmetzger** [comment]
Hey @vasia, I gave you push permissions to the repository, so that you can react more flexible to your student's needs. 
Remember, "with great power comes great responsibility" ;)

**Comment by vasia** [comment]
Thank you @rmetzger :) First lab was successfully completed already!

**Pull request merged**
